defmodule Colt.Repo.Migrations.CompaniesAndAnnualReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :registry_code, :text, null: false
      add :market, :text, null: false
      add :name, :text, null: false
      add :region, :text
      add :industry_code, :text
      add :status, :text, null: false, default: "registered"
      add :website_url, :text
      add :website_source, :text
      add :generic_email, :text
      add :ai_summary, :text
      add :last_enriched_at, :utc_datetime_usec
      add :revenue_latest, :decimal
      add :employees_latest, :bigint
      add :revenue_growth_bucket, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:companies, [:registry_code, :market],
             name: "companies_registry_code_market_index"
           )

    create table(:annual_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :year, :bigint, null: false
      add :revenue_eur, :decimal
      add :employees, :bigint
      add :source, :text, null: false, default: "rik"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "annual_reports_company_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:annual_reports, [:company_id, :year],
             name: "annual_reports_company_year_index"
           )
  end

  def down do
    drop constraint(:annual_reports, "annual_reports_company_id_fkey")

    drop_if_exists unique_index(:annual_reports, [:company_id, :year],
                     name: "annual_reports_company_year_index"
                   )

    drop table(:annual_reports)

    drop_if_exists unique_index(:companies, [:registry_code, :market],
                     name: "companies_registry_code_market_index"
                   )

    drop table(:companies)
  end
end
