defmodule Colt.Repo.Migrations.ActiveDefaultOn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sequences) do
      modify :enabled, :boolean, default: true
    end

    # `enabled` now means "active in the A/B rotation" (was a paused-by-default
    # auto-approve pool). Activate existing variants so the rotation has arms.
    execute("UPDATE sequences SET enabled = true", "")
  end

  def down do
    alter table(:sequences) do
      modify :enabled, :boolean, default: false
    end
  end
end
