defmodule Colt.Repo.Migrations.DropWeightDefaultAutoOff do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sequences) do
      remove :weight
      modify :enabled, :boolean, default: false
    end

    # `enabled` now means "auto-approve this sequence" (was "in the pool",
    # defaulted on). Reset existing rows to off so nothing auto-sends until
    # the user opts a sequence in.
    execute("UPDATE sequences SET enabled = false", "")
  end

  def down do
    alter table(:sequences) do
      modify :enabled, :boolean, default: true
      add :weight, :bigint, null: false, default: 1
    end
  end
end
