defmodule Colt.Repo.Migrations.AddRegistryEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Known shared-inbox prefixes. Only used to decide what the backfill may LEAVE
  # in :generic_email — not to classify anything. Anything cleared here is
  # recoverable: it survives in :registry_email and the AI classifier re-promotes
  # it to the generic rung if it turns out to be a shared inbox after all.
  @generic_prefixes ~w(info contact hello sales hi kontakt myynti office mail
                       admin legal clients support help team reception)

  def up do
    alter table(:companies) do
      add :registry_email, :text
      add :registry_email_kind, :text
    end

    # Backfill. Until now the EE ingest wrote the registry EMAIL contact-means
    # into :generic_email, and the landing scrape overwrote it with a scraped
    # info@ — so the column holds a mix of both with no way to tell them apart.
    # EE is the only market whose importer captures an email at all, so this is
    # scoped to :ee.
    execute(
      """
      UPDATE companies
         SET registry_email = generic_email
       WHERE market = 'ee'
         AND generic_email IS NOT NULL
         AND registry_email IS NULL
      """,
      ""
    )

    # :generic_email now means strictly "the info@-style inbox scraped from the
    # company's own site". A personal address sitting in it would wrongly serve
    # the generic-inbox rung, so drop anything that isn't plausibly an inbox.
    # Scraped values always match ExtractGenericEmail's keyword list, so this
    # only clears registry-sourced personal addresses — which are now safely in
    # :registry_email.
    execute(
      """
      UPDATE companies
         SET generic_email = NULL
       WHERE market = 'ee'
         AND generic_email IS NOT NULL
         AND lower(split_part(generic_email, '@', 1)) NOT IN (#{generic_prefix_list()})
      """,
      ""
    )
  end

  def down do
    # Put the registry address back where it came from, so a re-run of the old
    # code path still finds it.
    execute(
      """
      UPDATE companies
         SET generic_email = registry_email
       WHERE market = 'ee'
         AND generic_email IS NULL
         AND registry_email IS NOT NULL
      """,
      ""
    )

    alter table(:companies) do
      remove :registry_email_kind
      remove :registry_email
    end
  end

  defp generic_prefix_list do
    Enum.map_join(@generic_prefixes, ", ", &"'#{&1}'")
  end
end
