defmodule Colt.Repo.Migrations.AddEmailAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:email_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :address, :text, null: false
      add :display_name, :text
      add :nylas_grant_id, :text
      add :tz, :text, null: false, default: "Europe/Tallinn"
      add :status, :text, null: false, default: "healthy"
      add :last_sync_at, :utc_datetime_usec
      add :paused_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "email_accounts_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:email_accounts, [:nylas_grant_id],
             name: "email_accounts_nylas_grant_index"
           )
  end

  def down do
    drop constraint(:email_accounts, "email_accounts_user_id_fkey")

    drop_if_exists unique_index(:email_accounts, [:nylas_grant_id],
                     name: "email_accounts_nylas_grant_index"
                   )

    drop table(:email_accounts)
  end
end
