defmodule Colt.Repo.Migrations.PhaseE12TrackingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_emails) do
      add :opens_count, :bigint, null: false, default: 0
      add :clicks_count, :bigint, null: false, default: 0
      add :tracking_synced_at, :utc_datetime_usec
    end

    alter table(:campaigns) do
      remove :tracking_domain
    end
  end

  def down do
    alter table(:campaigns) do
      add :tracking_domain, :text
    end

    alter table(:outbound_emails) do
      remove :tracking_synced_at
      remove :clicks_count
      remove :opens_count
    end
  end
end
