defmodule Colt.Repo.Migrations.AddDeckTakes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deck_takes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slide_key, :text, null: false
      add :variant, :text
      add :media_url, :text, null: false
      add :media_content_type, :text, null: false
      add :poster_url, :text
      add :duration_ms, :bigint
      add :active?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:deck_takes)
  end
end
