defmodule Colt.Repo.Migrations.AddContactRungs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :reach_owner?, :boolean, null: false, default: true
      add :reach_title?, :boolean, null: false, default: true
      add :reach_generic?, :boolean, null: false, default: false
      add :require_website?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:campaigns) do
      remove :require_website?
      remove :reach_generic?
      remove :reach_title?
      remove :reach_owner?
    end
  end
end
