defmodule Colt.Repo.Migrations.PhaseE9WriterMeta do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_emails) do
      add :writer_meta, :map, default: %{}
    end
  end

  def down do
    alter table(:outbound_emails) do
      remove :writer_meta
    end
  end
end
