defmodule Colt.Repo.Migrations.FailureStage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_companies) do
      add :failed_stage, :text
    end
  end

  def down do
    alter table(:campaign_companies) do
      remove :failed_stage
    end
  end
end
