defmodule Colt.Repo.Migrations.AddPickedEmailDedup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_companies) do
      add :picked_email, :text
    end

    create unique_index(:campaign_companies, [:campaign_id, :picked_email],
             name: "campaign_companies_campaign_picked_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:campaign_companies, [:campaign_id, :picked_email],
                     name: "campaign_companies_campaign_picked_email_index"
                   )

    alter table(:campaign_companies) do
      remove :picked_email
    end
  end
end
