defmodule Colt.Repo.Migrations.AddBusinessModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :business_model, :text, null: false, default: "both"
    end
  end

  def down do
    alter table(:campaigns) do
      remove :business_model
    end
  end
end
