defmodule Colt.Repo.Migrations.AddSalesStages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sales_stages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0
      add :kind, :text, null: false, default: "active"
      add :color, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "sales_stages_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:campaign_contacts) do
      add :sales_stage_id,
          references(:sales_stages,
            column: :id,
            name: "campaign_contacts_sales_stage_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:campaign_contacts, "campaign_contacts_sales_stage_id_fkey")

    alter table(:campaign_contacts) do
      remove :sales_stage_id
    end

    drop constraint(:sales_stages, "sales_stages_campaign_id_fkey")

    drop table(:sales_stages)
  end
end
