defmodule Colt.Repo.Migrations.AdminClientProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :full_name, :text
      add :phone, :text
      add :company_name, :text
      add :company_reg_code, :text
      add :country, :text
      add :website, :text
      add :admin_notes, :text

      add :person_id,
          references(:persons,
            column: :id,
            name: "users_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "users_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_person_id_fkey")

    drop constraint(:users, "users_company_id_fkey")

    alter table(:users) do
      remove :company_id
      remove :person_id
      remove :admin_notes
      remove :website
      remove :country
      remove :company_reg_code
      remove :company_name
      remove :phone
      remove :full_name
    end
  end
end
