defmodule Colt.Repo.Migrations.OneClipPerSlide do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deck_takes) do
      remove :active?
      remove :variant
    end

    create unique_index(:deck_takes, [:slide_key], name: "deck_takes_one_per_slide_index")
  end

  def down do
    drop_if_exists unique_index(:deck_takes, [:slide_key], name: "deck_takes_one_per_slide_index")

    alter table(:deck_takes) do
      add :variant, :text
      add :active?, :boolean, null: false, default: true
    end
  end
end
