defmodule Colt.Repo.Migrations.AddIcpLearnings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:icp_learnings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "icp_learnings_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :source_company_id,
          references(:companies,
            column: :id,
            name: "icp_learnings_source_company_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:icp_learnings, "icp_learnings_campaign_id_fkey")

    drop constraint(:icp_learnings, "icp_learnings_source_company_id_fkey")

    drop table(:icp_learnings)
  end
end
