defmodule Colt.Repo.Migrations.AddSuppressedDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:suppressed_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "suppressed_domains_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:suppressed_domains, [:campaign_id, :domain],
             name: "suppressed_domains_campaign_domain_index"
           )
  end

  def down do
    drop constraint(:suppressed_domains, "suppressed_domains_campaign_id_fkey")

    drop_if_exists unique_index(:suppressed_domains, [:campaign_id, :domain],
                     name: "suppressed_domains_campaign_domain_index"
                   )

    drop table(:suppressed_domains)
  end
end
