defmodule Colt.Repo.Migrations.PhaseE6SplitInboundOutbound do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:emails)

    create table(:outbound_emails, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :step_position, :bigint
      add :ai_subject, :text
      add :ai_body, :text
      add :user_subject, :text
      add :user_body, :text
      add :is_manual_reply, :boolean, null: false, default: false
      add :status, :text, null: false, default: "drafted"
      add :scheduled_at, :utc_datetime_usec
      add :sent_at, :utc_datetime_usec
      add :nylas_message_id, :text
      add :nylas_thread_id, :text
      add :bounce_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :thread_id,
          references(:threads,
            column: :id,
            name: "outbound_emails_thread_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :email_account_id,
          references(:email_accounts,
            column: :id,
            name: "outbound_emails_email_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:outbound_emails, [:nylas_message_id],
             name: "outbound_emails_unique_nylas_message_index"
           )

    create table(:inbound_emails, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_address, :text, null: false
      add :subject, :text
      add :body, :text
      add :received_at, :utc_datetime_usec, null: false
      add :nylas_message_id, :text
      add :nylas_thread_id, :text
      add :reply_category, :text
      add :auto_attached?, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :thread_id,
          references(:threads,
            column: :id,
            name: "inbound_emails_thread_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :email_account_id,
          references(:email_accounts,
            column: :id,
            name: "inbound_emails_email_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:inbound_emails, [:nylas_message_id],
             name: "inbound_emails_unique_nylas_message_index"
           )
  end

  def down do
    drop constraint(:inbound_emails, "inbound_emails_thread_id_fkey")

    drop constraint(:inbound_emails, "inbound_emails_email_account_id_fkey")

    drop_if_exists unique_index(:inbound_emails, [:nylas_message_id],
                     name: "inbound_emails_unique_nylas_message_index"
                   )

    drop table(:inbound_emails)

    drop constraint(:outbound_emails, "outbound_emails_thread_id_fkey")

    drop constraint(:outbound_emails, "outbound_emails_email_account_id_fkey")

    drop_if_exists unique_index(:outbound_emails, [:nylas_message_id],
                     name: "outbound_emails_unique_nylas_message_index"
                   )

    drop table(:outbound_emails)
  end
end
