defmodule Colt.Repo.Migrations.AddCampaignContactAssignedTo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_contacts) do
      add :assigned_to_id,
          references(:users,
            column: :id,
            name: "campaign_contacts_assigned_to_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:campaign_contacts, "campaign_contacts_assigned_to_id_fkey")

    alter table(:campaign_contacts) do
      remove :assigned_to_id
    end
  end
end
