defmodule Colt.Repo.Migrations.AddSalesFunnelIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:status_events, [:thread_id])

    create index(:sales_stages, [:campaign_id])

    create index(:campaign_contacts, [:sales_stage_id])
  end

  def down do
    drop_if_exists index(:campaign_contacts, [:sales_stage_id])

    drop_if_exists index(:sales_stages, [:campaign_id])

    drop_if_exists index(:status_events, [:thread_id])
  end
end
