defmodule Colt.Repo.Migrations.DemoStepStamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_contacts) do
      add :demo_started_at, :utc_datetime
      add :demo_completed_at, :utc_datetime
      add :demo_cta_at, :utc_datetime
    end
  end

  def down do
    alter table(:campaign_contacts) do
      remove :demo_cta_at
      remove :demo_completed_at
      remove :demo_started_at
    end
  end
end
