defmodule Colt.Repo.Migrations.AddSequenceToOutboundEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_emails) do
      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "outbound_emails_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:outbound_emails, "outbound_emails_sequence_id_fkey")

    alter table(:outbound_emails) do
      remove :sequence_id
    end
  end
end
