defmodule Colt.Repo.Migrations.AddSkippedWebsite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_companies) do
      add :skipped_website?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:campaign_companies) do
      remove :skipped_website?
    end
  end
end
