defmodule Colt.Repo.Migrations.AddBillingToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :stripe_customer_id, :text
      add :monthly_contact_capacity, :bigint, null: false, default: 0
      add :subscription_period_start, :utc_datetime
      add :subscription_period_end, :utc_datetime
      add :subscription_status, :text, null: false, default: "none"
    end
  end

  def down do
    alter table(:users) do
      remove :subscription_status
      remove :subscription_period_end
      remove :subscription_period_start
      remove :monthly_contact_capacity
      remove :stripe_customer_id
    end
  end
end
