defmodule Colt.Repo.Migrations.AddFailureDetail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_companies) do
      add :failure_detail, :text
    end
  end

  def down do
    alter table(:campaign_companies) do
      remove :failure_detail
    end
  end
end
