defmodule Colt.Repo.Migrations.AddDemoLeads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:demo_leads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :name, :text
      add :phone, :text
      add :email, :text
      add :message, :text
      add :variant, :text
      add :visitor_id, :text
      add :slide, :text
      add :status, :text, null: false, default: "new"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_contact_id,
          references(:campaign_contacts,
            column: :id,
            name: "demo_leads_campaign_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:demo_leads, "demo_leads_campaign_contact_id_fkey")

    drop table(:demo_leads)
  end
end
