defmodule Colt.Repo.Migrations.SalesChecklistAndNextAction do
  @moduledoc """
  The sales funnel stops being a set of user-defined stages and becomes a
  date-driven work queue.

  Hand-edited on top of the autogenerated diff, because two things had to
  survive and the generator knows about neither:

    * `sales_stages` is **renamed** into `checklist_items` rather than dropped
      and recreated, so the item names the user already wrote are kept.
    * Contacts sitting in a `won`/`lost` stage have that outcome **copied onto
      the contact** before the stage link disappears. Without this step every
      closed deal would silently reopen.

  Contacts in an active stage get no outcome and no date, so they land in the
  Now bucket — correct, since none of them has ever been given a next action.
  """

  use Ecto.Migration

  def up do
    # ── 1. sales_stages becomes checklist_items ────────────────────────
    # Renaming keeps the rows; Postgres keeps the old index/constraint names
    # through a rename, so those are renamed too or the next generated
    # migration won't line up with them.
    rename table(:sales_stages), to: table(:checklist_items)

    execute "ALTER INDEX sales_stages_pkey RENAME TO checklist_items_pkey"

    execute "ALTER INDEX sales_stages_campaign_id_index RENAME TO checklist_items_campaign_id_index"

    execute "ALTER TABLE checklist_items RENAME CONSTRAINT sales_stages_campaign_id_fkey TO checklist_items_campaign_id_fkey"

    # ── 2. the contact's own sales state ───────────────────────────────
    alter table(:campaign_contacts) do
      add :next_action_at, :utc_datetime
      add :outcome, :text
      add :outcome_reason, :text
      add :outcome_at, :utc_datetime
    end

    # ── 3. carry won/lost across before the stage link goes ────────────
    # outcome_at is approximated from updated_at — the closing timestamp was
    # never stored separately. The original lost reasons stay readable on the
    # thread's StatusEvent feed.
    execute(
      """
      UPDATE campaign_contacts cc
      SET outcome = ci.kind, outcome_at = cc.updated_at
      FROM checklist_items ci
      WHERE cc.sales_stage_id = ci.id AND ci.kind IN ('won', 'lost')
      """,
      ""
    )

    # ── 4. won/lost were never checklist items ─────────────────────────
    execute("DELETE FROM checklist_items WHERE kind <> 'active'", "")

    alter table(:checklist_items) do
      remove :kind
      remove :color
    end

    # ── 5. the stage link is now dead weight ───────────────────────────
    drop_if_exists index(:campaign_contacts, [:sales_stage_id])

    alter table(:campaign_contacts) do
      remove :sales_stage_id
    end

    create index(:campaign_contacts, [:campaign_id, :next_action_at])

    # ── 6. the per-contact ticks ───────────────────────────────────────
    create table(:contact_checklist_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :done_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_contact_id,
          references(:campaign_contacts,
            column: :id,
            name: "contact_checklist_items_campaign_contact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :checklist_item_id, :uuid
      add :done_by_id, :uuid
    end

    create index(:contact_checklist_items, [:campaign_contact_id])

    create unique_index(:contact_checklist_items, [:campaign_contact_id, :checklist_item_id],
             name: "contact_checklist_items_unique_per_contact_item_index"
           )

    alter table(:contact_checklist_items) do
      modify :checklist_item_id,
             references(:checklist_items,
               column: :id,
               name: "contact_checklist_items_checklist_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :done_by_id,
             references(:users,
               column: :id,
               name: "contact_checklist_items_done_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  # Structurally reversible, but lossy in the same places `up` is additive:
  # the deleted Won/Lost stage rows don't come back, so rolling back leaves
  # closed contacts with a null sales_stage_id. The outcome data itself is
  # gone with the columns.
  def down do
    drop table(:contact_checklist_items)

    drop_if_exists index(:campaign_contacts, [:campaign_id, :next_action_at])

    alter table(:campaign_contacts) do
      remove :outcome_at
      remove :outcome_reason
      remove :outcome
      remove :next_action_at
    end

    alter table(:checklist_items) do
      add :kind, :text, null: false, default: "active"
      add :color, :text
    end

    execute "ALTER TABLE checklist_items RENAME CONSTRAINT checklist_items_campaign_id_fkey TO sales_stages_campaign_id_fkey"

    execute "ALTER INDEX checklist_items_campaign_id_index RENAME TO sales_stages_campaign_id_index"

    execute "ALTER INDEX checklist_items_pkey RENAME TO sales_stages_pkey"

    rename table(:checklist_items), to: table(:sales_stages)

    alter table(:campaign_contacts) do
      add :sales_stage_id,
          references(:sales_stages,
            column: :id,
            name: "campaign_contacts_sales_stage_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:campaign_contacts, [:sales_stage_id])
  end
end
