defmodule Colt.Repo.Migrations.AddVerifyStage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:persons) do
      add :email_verification_status, :text
      add :email_verified_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:persons) do
      remove :email_verified_at
      remove :email_verification_status
    end
  end
end
