defmodule Colt.Repo.Migrations.AddManualContacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_contacts) do
      add :in_funnel_sending?, :boolean, null: false, default: true
      add :in_funnel_sales?, :boolean, null: false, default: false
      add :origin, :text, null: false, default: "enrichment"
    end

    # Backfill: contacts already in a sales stage are in the sales funnel.
    execute(
      "UPDATE campaign_contacts SET \"in_funnel_sales?\" = true WHERE sales_stage_id IS NOT NULL"
    )
  end

  def down do
    alter table(:campaign_contacts) do
      remove :origin
      remove :in_funnel_sales?
      remove :in_funnel_sending?
    end
  end
end
