defmodule Colt.Repo.Migrations.CompaniesFilterIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:companies, [:market, :revenue_latest],
             name: "companies_market_revenue_registered_index",
             concurrently: true,
             where: "status = 'registered'"
           )

    create index(:companies, [:market, :employees_latest],
             name: "companies_market_employees_registered_index",
             concurrently: true,
             where: "status = 'registered'"
           )

    create index(:companies, [:market, :revenue_growth_bucket],
             name: "companies_market_growth_registered_index",
             concurrently: true,
             where: "status = 'registered'"
           )

    create index(:companies, [:market, :industry_code],
             name: "companies_market_industry_registered_index",
             concurrently: true,
             where: "status = 'registered'"
           )
  end

  def down do
    drop_if_exists index(:companies, [:market, :industry_code],
                     name: "companies_market_industry_registered_index"
                   )

    drop_if_exists index(:companies, [:market, :revenue_growth_bucket],
                     name: "companies_market_growth_registered_index"
                   )

    drop_if_exists index(:companies, [:market, :employees_latest],
                     name: "companies_market_employees_registered_index"
                   )

    drop_if_exists index(:companies, [:market, :revenue_latest],
                     name: "companies_market_revenue_registered_index"
                   )
  end
end
