defmodule Colt.Repo.Migrations.AdminClientIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:revenue_entries, [:user_id, :month])

    create index(:api_calls, [:inserted_at])

    create index(:api_calls, [:campaign_id])
  end

  def down do
    drop_if_exists index(:api_calls, [:campaign_id])

    drop_if_exists index(:api_calls, [:inserted_at])

    drop_if_exists index(:revenue_entries, [:user_id, :month])
  end
end
