defmodule Colt.Repo.Migrations.AddLearningTarget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:icp_learnings) do
      add :target, :text, null: false, default: "company"
    end
  end

  def down do
    alter table(:icp_learnings) do
      remove :target
    end
  end
end
