defmodule Colt.Repo.Migrations.AddWebsiteSearchAndPickedPerson do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:companies) do
      add :website_search_attempted_at, :utc_datetime_usec
    end

    alter table(:campaign_companies) do
      add :picked_person_id,
          references(:persons,
            column: :id,
            name: "campaign_companies_picked_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:campaign_companies, "campaign_companies_picked_person_id_fkey")

    alter table(:campaign_companies) do
      remove :picked_person_id
    end

    alter table(:companies) do
      remove :website_search_attempted_at
    end
  end
end
