defmodule Colt.Repo.Migrations.AddTargetContactCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :target_contact_count, :bigint, null: false, default: 100
    end
  end

  def down do
    alter table(:campaigns) do
      remove :target_contact_count
    end
  end
end
