defmodule Colt.Repo.Migrations.DropMatchesTargetTitle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:persons) do
      remove :matches_target_title
    end
  end

  def down do
    alter table(:persons) do
      add :matches_target_title, :boolean, default: false
    end
  end
end
