defmodule Colt.Repo.Migrations.AddApiCallTask do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_calls) do
      add :task, :text
    end
  end

  def down do
    alter table(:api_calls) do
      remove :task
    end
  end
end
