defmodule Colt.Repo.Migrations.UniqueStepPerThread do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:outbound_emails, [:thread_id, :step_position],
             name: "outbound_emails_step_per_thread_index"
           )
  end

  def down do
    drop_if_exists unique_index(:outbound_emails, [:thread_id, :step_position],
                     name: "outbound_emails_step_per_thread_index"
                   )
  end
end
