defmodule Colt.Repo.Migrations.CampaignCompanyIcpReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_companies) do
      add :icp_reason, :text
    end
  end

  def down do
    alter table(:campaign_companies) do
      remove :icp_reason
    end
  end
end
