defmodule Colt.Repo.Migrations.PhaseE3CampaignContactsThreadsEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:threads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :nylas_thread_id, :text
      add :last_activity_at, :utc_datetime_usec
      add :manual_status_override, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_contact_id, :uuid, null: false
    end

    create unique_index(:threads, [:campaign_contact_id], name: "threads_one_per_contact_index")

    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :thread_id,
          references(:threads,
            column: :id,
            name: "notes_thread_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "notes_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:emails, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :direction, :text, null: false
      add :step_position, :bigint
      add :ai_subject, :text
      add :ai_body, :text
      add :user_subject, :text
      add :user_body, :text
      add :is_manual_reply, :boolean, null: false, default: false
      add :status, :text, null: false, default: "drafted"
      add :scheduled_at, :utc_datetime_usec
      add :sent_at, :utc_datetime_usec
      add :nylas_message_id, :text
      add :nylas_thread_id, :text
      add :reply_category, :text
      add :bounce_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :thread_id,
          references(:threads,
            column: :id,
            name: "emails_thread_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :email_account_id,
          references(:email_accounts,
            column: :id,
            name: "emails_email_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:emails, [:nylas_message_id], name: "emails_unique_nylas_message_index")

    create table(:campaign_contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:threads) do
      modify :campaign_contact_id,
             references(:campaign_contacts,
               column: :id,
               name: "threads_campaign_contact_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:campaign_contacts) do
      add :status, :text, null: false, default: "pending_approval"
      add :sequence_snapshot, :map
      add :sequence_version, :bigint
      add :reply_category, :text
      add :auto_approved?, :boolean, null: false, default: false
      add :approved_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "campaign_contacts_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :person_id,
          references(:persons,
            column: :id,
            name: "campaign_contacts_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :assigned_email_account_id,
          references(:email_accounts,
            column: :id,
            name: "campaign_contacts_assigned_email_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:campaign_contacts, [:campaign_id, :person_id],
             name: "campaign_contacts_unique_per_campaign_index"
           )
  end

  def down do
    drop constraint(:campaign_contacts, "campaign_contacts_campaign_id_fkey")

    drop constraint(:campaign_contacts, "campaign_contacts_person_id_fkey")

    drop constraint(:campaign_contacts, "campaign_contacts_assigned_email_account_id_fkey")

    drop_if_exists unique_index(:campaign_contacts, [:campaign_id, :person_id],
                     name: "campaign_contacts_unique_per_campaign_index"
                   )

    alter table(:campaign_contacts) do
      remove :assigned_email_account_id
      remove :person_id
      remove :campaign_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :approved_at
      remove :auto_approved?
      remove :reply_category
      remove :sequence_version
      remove :sequence_snapshot
      remove :status
    end

    drop constraint(:threads, "threads_campaign_contact_id_fkey")

    alter table(:threads) do
      modify :campaign_contact_id, :uuid
    end

    drop table(:campaign_contacts)

    drop constraint(:emails, "emails_thread_id_fkey")

    drop constraint(:emails, "emails_email_account_id_fkey")

    drop_if_exists unique_index(:emails, [:nylas_message_id],
                     name: "emails_unique_nylas_message_index"
                   )

    drop table(:emails)

    drop constraint(:notes, "notes_thread_id_fkey")

    drop constraint(:notes, "notes_author_id_fkey")

    drop table(:notes)

    drop_if_exists unique_index(:threads, [:campaign_contact_id],
                     name: "threads_one_per_contact_index"
                   )

    drop table(:threads)
  end
end
