defmodule Colt.Repo.Migrations.AddRevenueEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:revenue_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :month, :text, null: false
      add :amount_usd, :decimal, null: false
      add :source, :text, null: false, default: "manual"
      add :note, :text
      add :stripe_invoice_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "revenue_entries_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:revenue_entries, [:stripe_invoice_id],
             name: "revenue_entries_unique_stripe_invoice_index"
           )
  end

  def down do
    drop constraint(:revenue_entries, "revenue_entries_user_id_fkey")

    drop_if_exists unique_index(:revenue_entries, [:stripe_invoice_id],
                     name: "revenue_entries_unique_stripe_invoice_index"
                   )

    drop table(:revenue_entries)
  end
end
