defmodule Colt.Repo.Migrations.AddPitch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pitches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain, :text
      add :ai_summary, :text
      add :user_summary, :text
      add :fetching?, :boolean, null: false, default: false
      add :fetch_ref, :text
      add :fetched_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "pitches_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:pitches, [:campaign_id], name: "pitches_one_per_campaign_index")
  end

  def down do
    drop constraint(:pitches, "pitches_campaign_id_fkey")

    drop_if_exists unique_index(:pitches, [:campaign_id], name: "pitches_one_per_campaign_index")

    drop table(:pitches)
  end
end
