defmodule Colt.Repo.Migrations.DropTemplateLabelFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:outbound_emails) do
      remove :template_offer
      remove :template_ask
      remove :template_angle
      remove :template_label
    end
  end

  def down do
    alter table(:outbound_emails) do
      add :template_label, :text
      add :template_angle, :text
      add :template_ask, :text
      add :template_offer, :text
    end
  end
end
