defmodule Colt.Repo.Migrations.AddPollHealthTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:email_accounts) do
      add :last_poll_success_at, :utc_datetime_usec
      add :last_poll_error_at, :utc_datetime_usec
      add :poll_failure_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:email_accounts) do
      remove :poll_failure_count
      remove :last_poll_error_at
      remove :last_poll_success_at
    end
  end
end
