defmodule Colt.Repo.Migrations.AddInboxFolderId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:email_accounts) do
      add :inbox_folder_id, :text
    end
  end

  def down do
    alter table(:email_accounts) do
      remove :inbox_folder_id
    end
  end
end
