defmodule Colt.Repo.Migrations.ApiCallPromptResponseSubject do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_calls) do
      add :prompt, :text
      add :response, :text
      add :subject_type, :text
      add :subject_id, :uuid
    end

    create index(:api_calls, [:subject_type, :subject_id])
  end

  def down do
    drop_if_exists index(:api_calls, [:subject_type, :subject_id])

    alter table(:api_calls) do
      remove :subject_id
      remove :subject_type
      remove :response
      remove :prompt
    end
  end
end
