defmodule Colt.Repo.Migrations.CampaignsPhase2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:campaigns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :icp_description, :text
      add :target_job_title, :text
      add :market, :text
      add :filters, :map, default: %{}
      add :status, :text, null: false, default: "draft"
      add :finalized_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "campaigns_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:campaign_companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :rejection_reason, :text
      add :included_in_export, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "campaign_companies_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :company_id,
          references(:companies,
            column: :id,
            name: "campaign_companies_company_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:campaign_companies, [:campaign_id, :company_id],
             name: "campaign_companies_campaign_company_index"
           )
  end

  def down do
    drop constraint(:campaign_companies, "campaign_companies_campaign_id_fkey")

    drop constraint(:campaign_companies, "campaign_companies_company_id_fkey")

    drop_if_exists unique_index(:campaign_companies, [:campaign_id, :company_id],
                     name: "campaign_companies_campaign_company_index"
                   )

    drop table(:campaign_companies)

    drop constraint(:campaigns, "campaigns_owner_id_fkey")

    drop table(:campaigns)
  end
end
