defmodule Colt.Repo.Migrations.Phase4aApiCallsPagesPersons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:persons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :title, :text
      add :email, :text
      add :phone, :text
      add :validated_in_markdown, :boolean, default: false
      add :matches_target_title, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "persons_company_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :source_page_id, :uuid
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:persons) do
      modify :source_page_id,
             references(:pages,
               column: :id,
               name: "persons_source_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:pages) do
      add :path, :text, null: false
      add :title, :text
      add :in_navigation, :boolean, default: false
      add :markdown, :text
      add :fetched_at, :utc_datetime_usec
      add :fetcher, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "pages_company_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:pages, [:company_id, :path], name: "pages_company_path_index")

    create table(:api_calls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :model, :text
      add :status, :text, null: false, default: "ok"
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cost_usd, :decimal
      add :latency_ms, :bigint
      add :cached, :boolean, default: false
      add :query, :text
      add :results_count, :bigint
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "api_calls_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:api_calls, "api_calls_campaign_id_fkey")

    drop table(:api_calls)

    drop constraint(:pages, "pages_company_id_fkey")

    drop_if_exists unique_index(:pages, [:company_id, :path], name: "pages_company_path_index")

    alter table(:pages) do
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :fetcher
      remove :fetched_at
      remove :markdown
      remove :in_navigation
      remove :title
      remove :path
    end

    drop constraint(:persons, "persons_source_page_id_fkey")

    alter table(:persons) do
      modify :source_page_id, :uuid
    end

    drop table(:pages)

    drop constraint(:persons, "persons_company_id_fkey")

    drop table(:persons)
  end
end
