defmodule Colt.Repo.Migrations.AddBucketChangedAtToCampaignContacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaign_contacts) do
      add :bucket_changed_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:campaign_contacts) do
      remove :bucket_changed_at
    end
  end
end
