defmodule Colt.Repo.Migrations.MergeTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sequences) do
      add :name, :text, null: false, default: "Untitled"
      add :weight, :bigint, null: false, default: 1
      add :enabled, :boolean, null: false, default: true
    end

    drop_if_exists unique_index(:sequences, [:campaign_id],
                     name: "sequences_one_per_campaign_index"
                   )

    alter table(:campaigns) do
      remove :auto_approve_streak
      remove :auto_approve_unlocked?
    end

    alter table(:campaign_contacts) do
      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "campaign_contacts_sequence_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    # Backfill: before this migration each campaign had exactly one sequence
    # (the old one_per_campaign singleton). Attribute existing contacts to it
    # so their prior user edits keep seeding that template's learning pool.
    execute(
      """
      UPDATE campaign_contacts cc
      SET sequence_id = s.id
      FROM sequences s
      WHERE s.campaign_id = cc.campaign_id
        AND cc.sequence_id IS NULL
      """,
      ""
    )
  end

  def down do
    drop constraint(:campaign_contacts, "campaign_contacts_sequence_id_fkey")

    alter table(:campaign_contacts) do
      remove :sequence_id
    end

    alter table(:campaigns) do
      add :auto_approve_unlocked?, :boolean, null: false, default: false
      add :auto_approve_streak, :bigint, null: false, default: 0
    end

    create unique_index(:sequences, [:campaign_id], name: "sequences_one_per_campaign_index")

    alter table(:sequences) do
      remove :enabled
      remove :weight
      remove :name
    end
  end
end
