defmodule Colt.Repo.Migrations.E2SequenceSending do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :language, :text, null: false, default: "en"
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "sequences_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:sequences, [:campaign_id], name: "sequences_one_per_campaign_index")

    create table(:sequence_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :kind, :text, null: false, default: "email"
      add :delay_days, :bigint, null: false, default: 2
      add :terminal_action, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "sequence_steps_sequence_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:sequence_steps, [:sequence_id, :position],
             name: "sequence_steps_position_per_sequence_index"
           )

    alter table(:email_accounts) do
      add :daily_quota, :bigint, null: false, default: 15
    end

    alter table(:campaigns) do
      add :sending_initialized?, :boolean, null: false, default: false
      add :panic_switch_on, :boolean, null: false, default: false
      add :auto_approve_unlocked?, :boolean, null: false, default: false
      add :auto_approve_on?, :boolean, null: false, default: false
      add :auto_approve_streak, :bigint, null: false, default: 0
      add :tracking_opens?, :boolean, null: false, default: false
      add :tracking_clicks?, :boolean, null: false, default: false
      add :tracking_domain, :text
    end

    create table(:campaign_email_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :paused?, :boolean, null: false, default: false
      add :paused_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "campaign_email_accounts_campaign_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :email_account_id,
          references(:email_accounts,
            column: :id,
            name: "campaign_email_accounts_email_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:campaign_email_accounts, [:campaign_id, :email_account_id],
             name: "campaign_email_accounts_unique_per_campaign_index"
           )
  end

  def down do
    drop constraint(:campaign_email_accounts, "campaign_email_accounts_campaign_id_fkey")

    drop constraint(:campaign_email_accounts, "campaign_email_accounts_email_account_id_fkey")

    drop_if_exists unique_index(:campaign_email_accounts, [:campaign_id, :email_account_id],
                     name: "campaign_email_accounts_unique_per_campaign_index"
                   )

    drop table(:campaign_email_accounts)

    alter table(:campaigns) do
      remove :tracking_domain
      remove :tracking_clicks?
      remove :tracking_opens?
      remove :auto_approve_streak
      remove :auto_approve_on?
      remove :auto_approve_unlocked?
      remove :panic_switch_on
      remove :sending_initialized?
    end

    alter table(:email_accounts) do
      remove :daily_quota
    end

    drop constraint(:sequence_steps, "sequence_steps_sequence_id_fkey")

    drop_if_exists unique_index(:sequence_steps, [:sequence_id, :position],
                     name: "sequence_steps_position_per_sequence_index"
                   )

    drop table(:sequence_steps)

    drop constraint(:sequences, "sequences_campaign_id_fkey")

    drop_if_exists unique_index(:sequences, [:campaign_id],
                     name: "sequences_one_per_campaign_index"
                   )

    drop table(:sequences)
  end
end
