defmodule Colt.Repo.Migrations.AddFeedbackUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feedback) do
      add :url, :text
    end
  end

  def down do
    alter table(:feedback) do
      remove :url
    end
  end
end
